import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:excel/excel.dart';
import 'package:file_saver/file_saver.dart';
import 'package:flutter/foundation.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import '../controllers/auth_controller.dart';
import '../models/event_model.dart';
import '../models/user_model.dart';
import 'activity_log_service.dart';

/// Builds an Excel (.xlsx) attendance report for a given event and saves it
/// via [FileSaver] which works on web (browser download) and native (file
/// system + share sheet).
///
/// The report contains two sheets:
///   * **Summary** — event metadata, totals (present / absent / total).
///   * **Attendance** — one row per in-scope user with status `Present` /
///     `Absent`, method, and timestamp.
class AttendanceExportService {
  static final FirebaseFirestore _db = FirebaseFirestore.instance;

  /// Generates and saves the attendance report. Returns the saved filename
  /// on success or null on failure (also surfaces a snackbar).
  static Future<String?> exportEventReport({
    required EventModel event,
    /// Restrict reporting scope. When null, all users are considered
    /// (leader use). When non-null, only users with `teamId == scopeTeamId`
    /// are included (supervisor use).
    String? scopeTeamId,
  }) async {
    try {
      // 1. Fetch all attendance records for the event.
      final attSnap = await _db
          .collection('attendance')
          .where('eventId', isEqualTo: event.eventId)
          .get();
      final attendanceMap = <String, _AttendanceRow>{};
      for (final d in attSnap.docs) {
        final data = d.data();
        final uid = (data['userId'] ?? '').toString();
        if (uid.isEmpty) continue;
        attendanceMap[uid] = _AttendanceRow(
          method: (data['method'] ?? 'qr').toString(),
          scannedAt: data['scannedAt'] is Timestamp
              ? (data['scannedAt'] as Timestamp).toDate()
              : null,
        );
      }

      // 2. Resolve the user scope.
      Query<Map<String, dynamic>> q = _db.collection('users');
      if (scopeTeamId != null && scopeTeamId.isNotEmpty) {
        q = q.where('teamId', isEqualTo: scopeTeamId);
      }
      final usersSnap = await q.get();
      final users = usersSnap.docs
          .map((d) => UserModel.fromFirestore(d))
          .where((u) => u.isActive)
          .toList()
        ..sort((a, b) => a.fullName
            .toLowerCase()
            .compareTo(b.fullName.toLowerCase()));

      // 3. Resolve team names once for nicer output.
      final teamNames = <String, String>{};
      final teamIds = users.map((u) => u.teamId).where((t) => t.isNotEmpty).toSet();
      for (final tid in teamIds) {
        try {
          final t = await _db.collection('teams').doc(tid).get();
          teamNames[tid] = (t.data()?['teamName'] ?? '').toString();
        } catch (_) {
          teamNames[tid] = '';
        }
      }

      // 4. Build the workbook.
      final excel = Excel.createExcel();
      // Excel.createExcel() seeds a default sheet "Sheet1"; we replace it.
      excel.rename('Sheet1', 'Attendance');
      final attSheet = excel['Attendance'];
      final summarySheet = excel['Summary'];

      // ── Summary sheet ────────────────────────────────────────────────
      final fmt = DateFormat('dd MMM yyyy, hh:mm a');
      final dateFmt = DateFormat('dd MMM yyyy');
      final presentCount = users.where((u) => attendanceMap.containsKey(u.uid)).length;
      final absentCount = users.length - presentCount;
      final percent = users.isEmpty
          ? '0%'
          : '${((presentCount / users.length) * 100).toStringAsFixed(1)}%';

      _writeSummary(summarySheet, [
        ['Taheri Committee — Attendance Report'],
        [],
        ['Event', event.title],
        ['Date', dateFmt.format(event.eventDate)],
        ['Location', event.location],
        ['Generated', fmt.format(DateTime.now())],
        ['Generated by', Get.find<AuthController>().displayName],
        ['Scope', scopeTeamId == null ? 'All members' : (teamNames[scopeTeamId] ?? scopeTeamId)],
        [],
        ['Total in scope', users.length],
        ['Present', presentCount],
        ['Absent', absentCount],
        ['Attendance rate', percent],
      ]);

      // ── Attendance sheet ─────────────────────────────────────────────
      final headers = [
        '#',
        'Name',
        'Email',
        'Mobile',
        'Role',
        'Team',
        'Status',
        'Method',
        'Marked At',
      ];
      attSheet.appendRow(headers.map((h) => TextCellValue(h)).toList());
      // Header styling.
      final headerStyle = CellStyle(
        bold: true,
        backgroundColorHex: ExcelColor.fromHexString('#1565C0'),
        fontColorHex: ExcelColor.fromHexString('#FFFFFF'),
        horizontalAlign: HorizontalAlign.Center,
      );
      for (var c = 0; c < headers.length; c++) {
        attSheet
            .cell(CellIndex.indexByColumnRow(columnIndex: c, rowIndex: 0))
            .cellStyle = headerStyle;
      }

      final presentStyle = CellStyle(
        backgroundColorHex: ExcelColor.fromHexString('#E8F5E9'),
        fontColorHex: ExcelColor.fromHexString('#1B5E20'),
        bold: true,
        horizontalAlign: HorizontalAlign.Center,
      );
      final absentStyle = CellStyle(
        backgroundColorHex: ExcelColor.fromHexString('#FFEBEE'),
        fontColorHex: ExcelColor.fromHexString('#B71C1C'),
        bold: true,
        horizontalAlign: HorizontalAlign.Center,
      );

      for (var i = 0; i < users.length; i++) {
        final u = users[i];
        final att = attendanceMap[u.uid];
        final isPresent = att != null;
        final row = <CellValue>[
          IntCellValue(i + 1),
          TextCellValue(u.fullName),
          TextCellValue(u.email),
          TextCellValue(u.mobile),
          TextCellValue(_roleLabel(u.role)),
          TextCellValue(teamNames[u.teamId] ?? ''),
          TextCellValue(isPresent ? 'Present' : 'Absent'),
          TextCellValue(isPresent ? att.method.toUpperCase() : '—'),
          TextCellValue(isPresent && att.scannedAt != null
              ? fmt.format(att.scannedAt!)
              : '—'),
        ];
        attSheet.appendRow(row);

        // Tint the Status cell by present/absent.
        attSheet
            .cell(CellIndex.indexByColumnRow(
                columnIndex: 6, rowIndex: i + 1))
            .cellStyle = isPresent ? presentStyle : absentStyle;
      }

      // Auto-size columns (excel package accepts width per col index).
      const widths = [4.0, 24.0, 28.0, 16.0, 14.0, 18.0, 12.0, 10.0, 22.0];
      for (var c = 0; c < widths.length; c++) {
        attSheet.setColumnWidth(c, widths[c]);
      }

      // 5. Encode + save.
      final bytes = excel.encode();
      if (bytes == null) {
        _err('Failed to encode workbook');
        return null;
      }

      final safeTitle = event.title
          .replaceAll(RegExp(r'[^A-Za-z0-9_-]+'), '_')
          .replaceAll(RegExp(r'_+'), '_');
      final dateTag = DateFormat('yyyyMMdd').format(event.eventDate);
      final filename = 'attendance_${safeTitle}_$dateTag';

      await FileSaver.instance.saveFile(
        name: filename,
        bytes: Uint8List.fromList(bytes),
        ext: 'xlsx',
        mimeType: MimeType.microsoftExcel,
      );

      // Audit log.
      try {
        await ActivityLogService.log(
          action: 'attendance_exported',
          targetId: event.eventId,
          targetType: 'event',
          targetName: event.title,
          note:
              'Present $presentCount / Absent $absentCount / Total ${users.length}',
        );
      } catch (_) {}

      Get.snackbar(
        'Report ready',
        '$filename.xlsx — $presentCount present, $absentCount absent.',
        snackPosition: SnackPosition.BOTTOM,
        duration: const Duration(seconds: 4),
      );
      return '$filename.xlsx';
    } catch (e, st) {
      debugPrint('Attendance export failed: $e\n$st');
      _err('Export failed: $e');
      return null;
    }
  }

  // ───────────────────────────────────────────────────────────────────────
  // Helpers
  // ───────────────────────────────────────────────────────────────────────
  static void _writeSummary(Sheet sheet, List<List<dynamic>> rows) {
    for (var r = 0; r < rows.length; r++) {
      final row = rows[r];
      for (var c = 0; c < row.length; c++) {
        final v = row[c];
        final cell = sheet.cell(
            CellIndex.indexByColumnRow(columnIndex: c, rowIndex: r));
        if (v is int) {
          cell.value = IntCellValue(v);
        } else if (v is double) {
          cell.value = DoubleCellValue(v);
        } else {
          cell.value = TextCellValue(v?.toString() ?? '');
        }
        if (r == 0) {
          cell.cellStyle = CellStyle(
            bold: true,
            fontSize: 14,
            fontColorHex: ExcelColor.fromHexString('#1565C0'),
          );
        } else if (c == 0) {
          cell.cellStyle = CellStyle(bold: true);
        }
      }
    }
    sheet.setColumnWidth(0, 22);
    sheet.setColumnWidth(1, 36);
  }

  static String _roleLabel(String role) {
    switch (role) {
      case 'leader':
      case 'admin':
        return 'Leader';
      case 'supervisor':
        return 'Supervisor';
      default:
        return 'Member';
    }
  }

  static void _err(String msg) {
    Get.snackbar('Error', msg, snackPosition: SnackPosition.BOTTOM);
  }
}

class _AttendanceRow {
  final String method;
  final DateTime? scannedAt;
  _AttendanceRow({required this.method, required this.scannedAt});
}
